{
  lib,
  config,
  pkgs,
  ...
}:
{
  # Headscale client setup.
  services.tailscale = {
    enable = true;
    package = pkgs.unstable.tailscale;
  };

  networking.firewall = {
    # Disable reverse path via same interface packet filtering
    checkReversePath = "loose";
    trustedInterfaces = [ "tailscale0" ];
    allowedUDPPorts = [ config.services.tailscale.port ];
  };

  # This creates a service "tailscale-online" that is up once we can bind the tailscale IPv4.
  # https://github.com/tailscale/tailscale/issues/11504
  # We don't simply rely on tailscaled.service because it is up before the IP is bindable.
  systemd.services.tailscale-online = {
    description = "Wait for Tailscale to have an IPv4 address";

    # [Unit]
    requires = [
      "systemd-networkd.service"
      "tailscaled.service"
    ];
    after = [
      "systemd-networkd.service"
      "tailscaled.service"
    ];
    bindsTo = [ "tailscaled.service" ];

    # [Service]
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;

      ExecStart = "${pkgs.systemd}/lib/systemd/systemd-networkd-wait-online -i tailscale0 -4";
    };
  };

  # nginx-config-reload.service (generated by the NixOS nginx module) has no
  # After=nginx.service ordering, so it races with nginx restarts triggered in
  # the same activation (e.g. after a nixpkgs bump that updates the nginx
  # package).  Adding After=nginx.service ensures the reload only fires once
  # nginx has fully restarted with its new binary.
  systemd.services.nginx-config-reload = lib.mkIf config.services.nginx.enable {
    after = [ "nginx.service" ];
  };

  # A client is added using the command:
  # sudo tailscale up --login-server headscale_server_url
}
